version: "3.5"
services:
  node:
    build: ./server
    ports:
      - "3003:${APP_PORT}"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - APP_PORT=$APP_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
  postgres:
    image: "postgres"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER

